### ISSUE TITLE
Conditional statements are reported as UnsupportedSpirv

### ISSUE THREAD

**Issue by swiftcoder** [PENGUINLIONG/spirq-rs#1]
The following line causes all boolean temporaries (i.e all conditions in if statements, for loops, etc) to be rejected as `UnsupportedSpirv`:

```
OP_TYPE_BOOL => return Err(Error::UnsupportedSpirv)
```

I presume this is here because boolean types aren't allowed in structs/buffers per the spec, but they are allowed as temporaries.

As a concrete example, this shader (taken from the SPIRV spec) currently can't be reflected:

```
#version 450

layout(location=0) in vec4 color1;
layout(location=1) in vec4 multiplier;
layout(location=2) noperspective in vec4 color2;

layout(location=0) out vec4 color;

struct S {
    bool b;
    vec4 v[5];
    int i;
};

layout(binding=0) uniform blockName {
    S s;
    bool cond;
};

void main()
{
    vec4 scale = vec4(1.0, 1.0, 2.0, 1.0);

    if (cond)
        color = color1 + s.v[2];
    else
        color = sqrt(color2) * scale;

    for (int i = 0; i < 4; ++i)
        color *= multiplier;
}
```

Any pointers on how to implement the boolean op code?

**Comment by PENGUINLIONG** [comment]
There was a design miss in type representations, that elementary types are not necessarily numeric but can also be logical like `bool`. In #2 and the incoming SPIR-Q 0.1.0 the coverage of elementary types are now broadened to include booleans. The fragment shader you privided have been added to the examples. Thanks for the report!
