### ISSUE TITLE
Update Spirv dependency & Support TaskEXT, MeshEXT execution models?

### ISSUE THREAD

**Issue by codecnotsupported** [PENGUINLIONG/spirq-rs#127]
I noticed that spirq's Spirv dependency is out of date when mapping `spirq::spirv::ExecutionModel` to `ash::vk::ShaderStageFlags` missing `TaskEXT`, `MeshEXT`.
Can the version be bumped?
https://github.com/PENGUINLIONG/spirq-rs/blob/da5102ea6b43933dff4511db5d9751de68b482d5/spirq-core/Cargo.toml#L22

**Comment by PENGUINLIONG** [comment]
Sure. Please feel free to make a pull request or I can help with that a couple of hours later.

**Comment by PENGUINLIONG** [comment]
It seems it's much more difficult than I thought to upgrade to spirv 0.3 since it removed all `FromPrimitive` impls.. Will deal with it a bit later

**Comment by codecnotsupported** [comment]
> It seems it's much more difficult than I thought to upgrade to spirv 0.3 since it removed all `FromPrimitive` impls.. Will deal with it a bit later

Thanks. I was struggling to make head & tails on how to deal with https://github.com/gfx-rs/rspirv/pull/219 as well.
