### ISSUE TITLE
gl_VertexIndex is treated as having location=0

### ISSUE THREAD

**Issue by fintelia** [PENGUINLIONG/spirq-rs#15]
Due to [this line](https://github.com/PENGUINLIONG/spirq-rs/blob/698e65cd8f0a0f5eb3d98a4a3a2298c0dcd3fa72/src/reflect.rs#L78), input/output variables without a location are treated as having location 0. This breaks code that also tries to use location 0 for its own purposes, because the real variable at that location can be overwritten by gl_VertexIndex or similar. I have a [commit](https://github.com/fintelia/spirq-rs/commit/7b80ba366f9c8eb94450ba5d119dd6d8effa2dd5) in my fork which discards these variables instead, but that doesn't seem like a great solution either.

**Comment by PENGUINLIONG** [comment]
`gl_VertexIndex` is a built-in variable, which will be decorated with `BuiltIn`. All variables decorated with `BuiltIn` should be dropped, since we don't actually have to specify them through APIs. - Although we should be checking for `BuiltIn`, your solution looks good enough for now.

**Comment by PENGUINLIONG** [comment]
#21
