### ISSUE TITLE
Modifying the shader interface

### ISSUE THREAD

**Issue by farnoy** [PENGUINLIONG/spirq-rs#40]
Is changing certain aspects of an `EntryPoint` planned as a feature? Would it be out of scope of this library? I think it would be great to have this as an option, allowing users of `spirq` to rebind especially descriptor sets, since it's impossible to do that with specialization constants.

My layman opinion is that these would require only slight changes in the bytestream to literal values.  These should not modify the sequence of the instruction stream, but there's probably something I'm not seeing.

**Comment by PENGUINLIONG** [comment]
SPIR-Q is restrained to support query only, post-processing is non-goal of this project. ;)
Though, AFAIK it's not necessary to rebind descriptors in SPIR-V because it's easier to achieve the same over API calls.

**Comment by farnoy** [comment]
That's too bad, but fair enough. 

If you're referring to making the decision at the `vkPipelineLayout` (and by association `vkDescriptorSetLayout`) level, then there's a performance incentive in keeping them compatible across different programs.
