### ISSUE TITLE
Error on specialization constant usage as compute dimension specifier

### ISSUE THREAD

**Issue by farnoy** [PENGUINLIONG/spirq-rs#41]
I believe this part is insufficient: https://github.com/PENGUINLIONG/spirq-rs/blob/09d9034b167168f0bdb684d2037092d25788d4eb/src/reflect.rs#L391-L394

The library can't seem to load a compute shader like this:

```glsl
#version 450

layout (local_size_x_id = 123) in;

void main() {
  // ...
}
```

I think it's expecting a direct reference to a decoration with the spec constant id, one that looks like this:

```
OpDecorate %variable_name SpecId 74
...
%variable_name = OpSpecConstant %uint 3
```

This gets generated when you use your typical `layout (constant_id = 74) const uint variable_name = 3;`

But the code generated for `local_size_x_id` breaks the pattern as follows:

```
                OpDecorate %494 SpecId 123
         %494 = OpSpecConstant %uint 1
 %gl_WorkGroupSize = OpSpecConstantComposite %v3uint %494 %uint_1 %uint_1
```

So I think there's one more jump needed.

**Comment by PENGUINLIONG** [comment]
Reviewed the spec and it sounds like we can safely ignore the composite one. Thanks for the detail.
