### ISSUE TITLE
Signed and Unsigned scalar type variants have the same Debug output

### ISSUE THREAD

**Issue by farnoy** [PENGUINLIONG/spirq-rs#55]
I found a small issue with the Debug implementation, I think Unsigned should format to `u{}` instead of `i{}`

https://github.com/PENGUINLIONG/spirq-rs/blob/1de21b2a8cb2686e721c57690401f8624d6e015d/src/ty.rs#L69

**Comment by PENGUINLIONG** [comment]
Nice catch! Will fix it soon.

**Comment by PENGUINLIONG** [comment]
This will be a part of the next minor release in which the documentation is too reviewed. Should be published this week. Stay tune :)

**Comment by farnoy** [comment]
Thanks for the quick fix!
