### ISSUE TITLE
Error on OpSpecConstantOp

### ISSUE THREAD

**Issue by farnoy** [PENGUINLIONG/spirq-rs#67]
Hi,

This is a similar issue to #41, the following fragment trips up spirq's reflection:

```llvm
%493 = OpSpecConstant %uint 1
%gl_WorkGroupSize = OpSpecConstantComposite %v3uint %493 %uint_1 %uint_1
; The next one is the culprit?
%495 = OpSpecConstantOp %uint CompositeExtract %gl_WorkGroupSize 0
%_arr_uint_495 = OpTypeArray %uint %495
%_ptr_Workgroup__arr_uint_495 = OpTypePointer Workgroup %_arr_uint_495
%test_shared_variable = OpVariable %_ptr_Workgroup__arr_uint_495 Workgroup
```

Which is generated from a GLSL fragment like this:

```glsl
layout (local_size_x_id = 1) in;

shared uint test_shared_variable[gl_WorkGroupSize.x];
```

**Comment by PENGUINLIONG** [comment]
never thought about such use case before.😂 will look into it.

**Comment by PENGUINLIONG** [comment]
So I actually *have* thought about it before and have even made a comment on this.

https://github.com/PENGUINLIONG/spirq-rs/blob/cc7cf79617b5c643ebca5313b21b8b671e7d9c67/src/reflect.rs#L423-L431

I asked about this probably last year to a Khronos member and according to them, it leads to undefined behavior to use specialization constant to specify array size. But if your shader works as expected on most platforms, it's probably worthy to follow such bad practice. So I probably need more time to check the *availability* of this *feature* on multiple platforms before *fixing* SPIR-Q.

**Comment by farnoy** [comment]
I haven't started using code like this, but it seemed like an obvious thing. I can see the AMD compiler recognizing it well offline, but I haven't tested by re-specializing the pipeline at runtime (it might "work" without adjusting the LDS allocation size for the pipeline, making the whole approach useless).

**Comment by PENGUINLIONG** [comment]
I see that `glslang` accepts such usage and frontends depending on glslang like `glslangValidator` and ShaderC certainly follows. I'm skimming through the specification to see if they have concrete words on this.

**Comment by PENGUINLIONG** [comment]
It seems your code is legal in Vulkan-flavored GLSL. The aforementioned note applies to UBOs and SSBOs because they need offset and stride decoration which cannot be derived from specialization constants, but on-chip memory is certainly nothing alike. I will work on supporting `OpSpecConstantOp` and your code should reflect in the next release. 🧙‍♂️

**Comment by farnoy** [comment]
That's great news! Thanks a lot for supporting this library, it's really
convenient.
