### ISSUE TITLE
Calling the same function twice is reported as CorruptedSpriv

### ISSUE THREAD

**Issue by swiftcoder** [PENGUINLIONG/spirq-rs#7]
If I define a helper function and then invoke it twice from main, the spirv is reported to be corrupted:

```
void do_something() {}

void main() {
    do_something();
    do_something();
}
```

**Comment by swiftcoder** [comment]
BTW, it would be really nice if the CorruptedSpirv error carried some context - I had to and logging to every place it occurs to find which opcode was causing the problem.

**Comment by PENGUINLIONG** [comment]
Seems there is a unneccessary [check](https://github.com/PENGUINLIONG/spirq-rs/blob/2972542a1efcf9ccebff4df0a1860966d63f5e16/src/reflect.rs#L431) that rejects multiple calls to a same function. :/

Thanks for the report!

**Comment by PENGUINLIONG** [comment]
Your code should be reflected correctly now. Will work on more contextual error report

**Comment by swiftcoder** [comment]
Awesome, thanks! My (extremely complicated) compute shaders are all supported now :)
