### ISSUE TITLE
Descriptor sets ignored in reflection

### ISSUE THREAD

**Issue by farnoy** [PENGUINLIONG/spirq-rs#70]
I noticed that if a descriptor binding is not used by a simple load/store, spirq seems to think it's not used and drops it. Here's an example shader that illustrates the problem:

```glsl
#version 450

layout(set = 1, binding = 0) buffer TestBinding {
    uint count;
} test;

void main() {
    atomicAdd(test.count, 1); // spirq entry_point.desc() is empty
    // test.count = 5; // This will make spirq "notice" it and the descriptor binding will be reflected
}
```

I was only using a certain descriptor binding with these atomics and I noticed spirq dropping it completely. I had to work around it by doing something that can be optimized away by the runtime compiler, like:

```glsl
if (gl_LocalInvocationIndex == 2048) // unreachable
  test.count = 0;
```

**Comment by PENGUINLIONG** [comment]
I see. I haven't considered atomic access before. Will be fixed soon.

**Comment by PENGUINLIONG** [comment]
#71 should have addressed the problem but atm i don't have much existing test samples with atomics. Could you switch to the current `dev` branch and see if it suits your needs?

**Comment by farnoy** [comment]
Yep, it fixed my case when I switched to the `dev` branch, thanks!
